config/routes.rb
Videosmash::Application.routes.draw do
  root to: "home#index"

  devise_for :users

  resources :videos, only: [] do
    member do
      post :view
    end
  end

end

app/models/genre.rb
class Genre
  include Mongoid::Document
  field :name, type: String
  # belongs_to :video
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  embeds_many :video_views

  def next_video_by genre
    viewed_titles = self.video_views.where(genre: genre).map(&:title)
    return Video.where(genre: genre).not_in(title: viewed_titles).sample
  end

  def viewed_by genre
    self.video_views.where(genre: genre).order_by(created_at: -1)
  end
end

app/models/video.rb
class Video
  include Mongoid::Document
  field :title, type: String
  field :genre, type: String
  field :colour, type: String
end

app/models/video_view.rb
class VideoView
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :genre, type: String

  belongs_to :video, inverse_of: nil
  embedded_in :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @genres = Genre.all
    if params[:genre]
      @current_genre = params[:genre][:genre_name]
      cookies[:current_genre] = @current_genre
    else
      if cookies[:current_genre]
        @current_genre = cookies[:current_genre]
      else
        @current_genre = @genres.sample.name
        cookies[:current_genre] = @current_genre
      end
    end

    @previously_viewed = current_user.viewed_by @current_genre
    @current_video = current_user.next_video_by @current_genre

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!

  def view
    video = Video.find(params[:id])
    @previous_view = current_user.video_views.create(video: video, genre: video.genre, title: video.title)

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<br />

<%= render partial: 'videos/current_video', locals: {current_video: @current_video}  %>

<br />

<h2>Previously Viewed</h2>
<hr />

<%= render partial: 'videos/previously_viewed', locals: {previously_viewed: @previously_viewed}  %>

app/views/home/index.js.erb
$('#current_video').replaceWith("<%= j render(partial: 'videos/current_video', locals: {current_video: @current_video}) %>");

$('#previously_viewed_list').replaceWith("<%= j render(partial: 'videos/previously_viewed', locals: {previously_viewed: @previously_viewed}) %>")

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to image_tag('logo.png'), root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <% if @genres %>
    <li>
      <%= form_tag("/", method: "get", remote: true, id: "genre_form", style: "display: inline;") do %>
        <%= select("genre", "genre_name", options_for_select(@genres.map { |g| g.name }, @current_genre)) %>
      <% end %>
    </li>
  <% end %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Videosmash" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Videosmash" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="app-cont">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>

  <footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </footer>
</html>

app/views/videos/_current_video.html.erb
<div id="current_video" class="app-cont-thin" >
  <% if current_video != nil %>
    <div class="video_placeholder" style="background-color: #<%= current_video.colour %>;">
    </div>
    <div class='video_info'>
      <%= form_for current_video, url: view_video_path(current_video), method: :post, remote: true do |f| %>
        <li id="current_video_name"><%= current_video.title %> (<%= current_video.genre %>)</li>
        <%= f.submit "Next New Video", class: "submit-button centered" %>
      <% end %>
    </div>
  <% else %>
    <p>We ran out of new videos for this category :(</p>
  <% end %>
</div>

app/views/videos/_line.html.erb
<ul>
  <div class="video-thumbnail">
  </div>
  <li class="video">
    <div class="col det">
      <span><strong><%= view.video.title %></strong> (<%= view.video.genre %>)</span>
      <p class="details">
        <span>Viewed:</span>
        <span><%= view.created_at %></span>
      </p>
    </div>
  </li>
</ul>

app/views/videos/_previously_viewed.html.erb
<div id="previously_viewed_list">
  <% if previously_viewed.count == 0 %>
    <p>
    <span>There aren't previously viewed videos</span>
    </p>
  <% end %>
  <% previously_viewed.each do |view| %>
    <%= render partial: 'videos/line', locals: {view: view} %>
  <% end %>
</div>

app/views/videos/view.js.erb
$('#previously_viewed_list').prepend("<%= j render(partial: 'videos/line', locals: {view: @previous_view}) %>")

$("#genre_form").trigger("submit.rails");